{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.977223, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 230, "message": "__repository__ - sensor_tiempos_error - ================================================================================", "module": "definitions", "msecs": 977.0, "msg": "__repository__ - sensor_tiempos_error - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124375.11229515076, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.9782271, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "                        AN\u00c1LISIS DE TIEMPOS DE EJECUCI\u00d3N                        ", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 231, "message": "__repository__ - sensor_tiempos_error -                         AN\u00c1LISIS DE TIEMPOS DE EJECUCI\u00d3N                        ", "module": "definitions", "msecs": 978.0, "msg": "__repository__ - sensor_tiempos_error -                         AN\u00c1LISIS DE TIEMPOS DE EJECUCI\u00d3N                        ", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124376.11651420593, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.9793978, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 232, "message": "__repository__ - sensor_tiempos_error - ================================================================================", "module": "definitions", "msecs": 979.0, "msg": "__repository__ - sensor_tiempos_error - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124377.28714942932, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.9793978, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 233, "message": "__repository__ - sensor_tiempos_error - ================================================================================", "module": "definitions", "msecs": 979.0, "msg": "__repository__ - sensor_tiempos_error - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124377.28714942932, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.9793978, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "                   EXPLORACI\u00d3N DE TODOS LOS TIPOS DE EVENTOS                    ", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 234, "message": "__repository__ - sensor_tiempos_error -                    EXPLORACI\u00d3N DE TODOS LOS TIPOS DE EVENTOS                    ", "module": "definitions", "msecs": 979.0, "msg": "__repository__ - sensor_tiempos_error -                    EXPLORACI\u00d3N DE TODOS LOS TIPOS DE EVENTOS                    ", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124377.28714942932, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:21 -0300", "created": 1743085641.9803996, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 235, "message": "__repository__ - sensor_tiempos_error - ================================================================================", "module": "definitions", "msecs": 980.0, "msg": "__repository__ - sensor_tiempos_error - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124378.2889842987, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
{"args": [], "asctime": "2025-03-27 11:27:22 -0300", "created": 1743085642.0256493, "dagster_meta": {"name": "sensor_tiempos_error", "orig_message": "Eventos de tipo DagsterEventType.STEP_FAILURE: EventLogConnection(records=[EventLogRecord(storage_id=88, event_log_entry=EventLogEntry(error_info=None, level=40, user_message='Execution of step \"print_valor\" failed.', run_id='545cc217-459f-41a9-b879-531a68fd7dc5', timestamp=1743085618.0184188, step_key='print_valor', job_name='new_job', dagster_event=DagsterEvent(event_type_value='STEP_FAILURE', job_name='new_job', step_handle=StepHandle(node_handle=NodeHandle(name='print_valor', parent=None), key='print_valor'), node_handle=NodeHandle(name='print_valor', parent=None), step_kind_value='COMPUTE', logging_tags={'job_name': 'new_job', 'op_name': 'print_valor', 'resource_fn_name': 'None', 'resource_name': 'None', 'run_id': '545cc217-459f-41a9-b879-531a68fd7dc5', 'step_key': 'print_valor'}, event_specific_data=StepFailureData(error=SerializableErrorInfo(message='dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op \"print_valor\":\\n', stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_plan.py\", line 245, in dagster_event_sequence_for_step\\n    yield from check.generator(step_events)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 501, in core_dagster_event_sequence_for_step\\n    for user_event in _step_output_error_checked_user_event_sequence(\\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 184, in _step_output_error_checked_user_event_sequence\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 88, in _process_asset_results_to_events\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 186, in execute_core_compute\\n    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 155, in _yield_compute_results\\n    for event in iterate_with_context(\\n                 ^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 478, in iterate_with_context\\n    with context_fn():\\n         ^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python312\\\\Lib\\\\contextlib.py\", line 158, in __exit__\\n    self.gen.throw(value)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 86, in op_execution_error_boundary\\n    raise error_cls(\\n'], cls_name='DagsterExecutionStepExecutionError', cause=SerializableErrorInfo(message=\"AttributeError: 'OpExecutionContext' object has no attribute 'ru'\\n\", stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 56, in op_execution_error_boundary\\n    yield\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 480, in iterate_with_context\\n    next_output = next(iterator)\\n                  ^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 127, in _coerce_op_compute_fn_to_iterator\\n    result = invoke_compute_fn(\\n             ^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 115, in invoke_compute_fn\\n    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\getting_started_etl_tutorial\\\\etl_tutorial\\\\definitions.py\", line 105, in print_valor\\n    run = context.ru\\n          ^^^^^^^^^^\\n'], cls_name='AttributeError', cause=None, context=None), context=None), user_failure_data=None, error_source=<ErrorSource.USER_CODE_ERROR: 'USER_CODE_ERROR'>), message='Execution of step \"print_valor\" failed.', pid=35748, step_key='print_valor')))], cursor='eyJ0eXBlIjogIlNUT1JBR0VfSUQiLCAidmFsdWUiOiA4OH0=', has_more=False)", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error", "levelname": "INFO", "levelno": 20, "lineno": 252, "message": "__repository__ - sensor_tiempos_error - Eventos de tipo DagsterEventType.STEP_FAILURE: EventLogConnection(records=[EventLogRecord(storage_id=88, event_log_entry=EventLogEntry(error_info=None, level=40, user_message='Execution of step \"print_valor\" failed.', run_id='545cc217-459f-41a9-b879-531a68fd7dc5', timestamp=1743085618.0184188, step_key='print_valor', job_name='new_job', dagster_event=DagsterEvent(event_type_value='STEP_FAILURE', job_name='new_job', step_handle=StepHandle(node_handle=NodeHandle(name='print_valor', parent=None), key='print_valor'), node_handle=NodeHandle(name='print_valor', parent=None), step_kind_value='COMPUTE', logging_tags={'job_name': 'new_job', 'op_name': 'print_valor', 'resource_fn_name': 'None', 'resource_name': 'None', 'run_id': '545cc217-459f-41a9-b879-531a68fd7dc5', 'step_key': 'print_valor'}, event_specific_data=StepFailureData(error=SerializableErrorInfo(message='dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op \"print_valor\":\\n', stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_plan.py\", line 245, in dagster_event_sequence_for_step\\n    yield from check.generator(step_events)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 501, in core_dagster_event_sequence_for_step\\n    for user_event in _step_output_error_checked_user_event_sequence(\\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 184, in _step_output_error_checked_user_event_sequence\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 88, in _process_asset_results_to_events\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 186, in execute_core_compute\\n    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 155, in _yield_compute_results\\n    for event in iterate_with_context(\\n                 ^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 478, in iterate_with_context\\n    with context_fn():\\n         ^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python312\\\\Lib\\\\contextlib.py\", line 158, in __exit__\\n    self.gen.throw(value)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 86, in op_execution_error_boundary\\n    raise error_cls(\\n'], cls_name='DagsterExecutionStepExecutionError', cause=SerializableErrorInfo(message=\"AttributeError: 'OpExecutionContext' object has no attribute 'ru'\\n\", stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 56, in op_execution_error_boundary\\n    yield\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 480, in iterate_with_context\\n    next_output = next(iterator)\\n                  ^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 127, in _coerce_op_compute_fn_to_iterator\\n    result = invoke_compute_fn(\\n             ^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 115, in invoke_compute_fn\\n    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\getting_started_etl_tutorial\\\\etl_tutorial\\\\definitions.py\", line 105, in print_valor\\n    run = context.ru\\n          ^^^^^^^^^^\\n'], cls_name='AttributeError', cause=None, context=None), context=None), user_failure_data=None, error_source=<ErrorSource.USER_CODE_ERROR: 'USER_CODE_ERROR'>), message='Execution of step \"print_valor\" failed.', pid=35748, step_key='print_valor')))], cursor='eyJ0eXBlIjogIlNUT1JBR0VfSUQiLCAidmFsdWUiOiA4OH0=', has_more=False)", "module": "definitions", "msecs": 25.0, "msg": "__repository__ - sensor_tiempos_error - Eventos de tipo DagsterEventType.STEP_FAILURE: EventLogConnection(records=[EventLogRecord(storage_id=88, event_log_entry=EventLogEntry(error_info=None, level=40, user_message='Execution of step \"print_valor\" failed.', run_id='545cc217-459f-41a9-b879-531a68fd7dc5', timestamp=1743085618.0184188, step_key='print_valor', job_name='new_job', dagster_event=DagsterEvent(event_type_value='STEP_FAILURE', job_name='new_job', step_handle=StepHandle(node_handle=NodeHandle(name='print_valor', parent=None), key='print_valor'), node_handle=NodeHandle(name='print_valor', parent=None), step_kind_value='COMPUTE', logging_tags={'job_name': 'new_job', 'op_name': 'print_valor', 'resource_fn_name': 'None', 'resource_name': 'None', 'run_id': '545cc217-459f-41a9-b879-531a68fd7dc5', 'step_key': 'print_valor'}, event_specific_data=StepFailureData(error=SerializableErrorInfo(message='dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op \"print_valor\":\\n', stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_plan.py\", line 245, in dagster_event_sequence_for_step\\n    yield from check.generator(step_events)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 501, in core_dagster_event_sequence_for_step\\n    for user_event in _step_output_error_checked_user_event_sequence(\\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 184, in _step_output_error_checked_user_event_sequence\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\execute_step.py\", line 88, in _process_asset_results_to_events\\n    for user_event in user_event_sequence:\\n                      ^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 186, in execute_core_compute\\n    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):\\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute.py\", line 155, in _yield_compute_results\\n    for event in iterate_with_context(\\n                 ^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 478, in iterate_with_context\\n    with context_fn():\\n         ^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python312\\\\Lib\\\\contextlib.py\", line 158, in __exit__\\n    self.gen.throw(value)\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 86, in op_execution_error_boundary\\n    raise error_cls(\\n'], cls_name='DagsterExecutionStepExecutionError', cause=SerializableErrorInfo(message=\"AttributeError: 'OpExecutionContext' object has no attribute 'ru'\\n\", stack=['  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\utils.py\", line 56, in op_execution_error_boundary\\n    yield\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_utils\\\\__init__.py\", line 480, in iterate_with_context\\n    next_output = next(iterator)\\n                  ^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 127, in _coerce_op_compute_fn_to_iterator\\n    result = invoke_compute_fn(\\n             ^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\venv\\\\Lib\\\\site-packages\\\\dagster\\\\_core\\\\execution\\\\plan\\\\compute_generator.py\", line 115, in invoke_compute_fn\\n    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\\n', '  File \"C:\\\\Users\\\\AxelRam\u00edrez\\\\Documents\\\\GitHub\\\\dagsters_tutorial\\\\getting_started_etl_tutorial\\\\etl_tutorial\\\\definitions.py\", line 105, in print_valor\\n    run = context.ru\\n          ^^^^^^^^^^\\n'], cls_name='AttributeError', cause=None, context=None), context=None), user_failure_data=None, error_source=<ErrorSource.USER_CODE_ERROR: 'USER_CODE_ERROR'>), message='Execution of step \"print_valor\" failed.', pid=35748, step_key='print_valor')))], cursor='eyJ0eXBlIjogIlNUT1JBR0VfSUQiLCAidmFsdWUiOiA4OH0=', has_more=False)", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 32412, "processName": "MainProcess", "relativeCreated": 124423.53868484497, "stack_info": null, "taskName": null, "thread": 6264, "threadName": "ThreadPoolExecutor-0_1"}
