{"args": [], "asctime": "2025-03-27 15:30:27 -0300", "created": 1743100227.0671115, "dagster_meta": {"name": "sensor_tiempos_error_df", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error_df", "levelname": "INFO", "levelno": 20, "lineno": 334, "message": "__repository__ - sensor_tiempos_error_df - ================================================================================", "module": "definitions", "msecs": 67.0, "msg": "__repository__ - sensor_tiempos_error_df - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 36232, "processName": "MainProcess", "relativeCreated": 44101.415395736694, "stack_info": null, "taskName": null, "thread": 11192, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "asctime": "2025-03-27 15:30:27 -0300", "created": 1743100227.0681114, "dagster_meta": {"name": "sensor_tiempos_error_df", "orig_message": "                          AN\u00c1LISIS DETALLADO DE ERROR                           ", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error_df", "levelname": "INFO", "levelno": 20, "lineno": 335, "message": "__repository__ - sensor_tiempos_error_df -                           AN\u00c1LISIS DETALLADO DE ERROR                           ", "module": "definitions", "msecs": 68.0, "msg": "__repository__ - sensor_tiempos_error_df -                           AN\u00c1LISIS DETALLADO DE ERROR                           ", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 36232, "processName": "MainProcess", "relativeCreated": 44102.415323257446, "stack_info": null, "taskName": null, "thread": 11192, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "asctime": "2025-03-27 15:30:27 -0300", "created": 1743100227.0681114, "dagster_meta": {"name": "sensor_tiempos_error_df", "orig_message": "================================================================================", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error_df", "levelname": "INFO", "levelno": 20, "lineno": 336, "message": "__repository__ - sensor_tiempos_error_df - ================================================================================", "module": "definitions", "msecs": 68.0, "msg": "__repository__ - sensor_tiempos_error_df - ================================================================================", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 36232, "processName": "MainProcess", "relativeCreated": 44102.415323257446, "stack_info": null, "taskName": null, "thread": 11192, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "asctime": "2025-03-27 15:30:27 -0300", "created": 1743100227.0734956, "dagster_meta": {"name": "sensor_tiempos_error_df", "orig_message": "\n\ud83d\udcca DataFrame de Errores:", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error_df", "levelname": "INFO", "levelno": 20, "lineno": 397, "message": "__repository__ - sensor_tiempos_error_df - \n\ud83d\udcca DataFrame de Errores:", "module": "definitions", "msecs": 73.0, "msg": "__repository__ - sensor_tiempos_error_df - \n\ud83d\udcca DataFrame de Errores:", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 36232, "processName": "MainProcess", "relativeCreated": 44107.7995300293, "stack_info": null, "taskName": null, "thread": 11192, "threadName": "ThreadPoolExecutor-0_0"}
{"args": [], "asctime": "2025-03-27 15:30:27 -0300", "created": 1743100227.0782905, "dagster_meta": {"name": "sensor_tiempos_error_df", "orig_message": "\n                                 run_id job_name     step_key                                                                                                                                                                                          error_location  linea_num                                                error_message error_code                     timestamp\n0  fe1d71c8-8485-4a9d-b9ee-051bfc6c4f86  new_job  print_valor  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 106, in print_valor\\n    print(f\"Valor: {var}\")\\n                    ^^^        106  NameError: name 'var' is not defined. Did you mean: 'vars'?    'vars'? 2025-03-27 18:30:09.391006470", "repository_name": "__repository__"}, "exc_info": null, "exc_text": null, "filename": "definitions.py", "funcName": "sensor_tiempos_error_df", "levelname": "INFO", "levelno": 20, "lineno": 398, "message": "__repository__ - sensor_tiempos_error_df - \n                                 run_id job_name     step_key                                                                                                                                                                                          error_location  linea_num                                                error_message error_code                     timestamp\n0  fe1d71c8-8485-4a9d-b9ee-051bfc6c4f86  new_job  print_valor  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 106, in print_valor\\n    print(f\"Valor: {var}\")\\n                    ^^^        106  NameError: name 'var' is not defined. Did you mean: 'vars'?    'vars'? 2025-03-27 18:30:09.391006470", "module": "definitions", "msecs": 78.0, "msg": "__repository__ - sensor_tiempos_error_df - \n                                 run_id job_name     step_key                                                                                                                                                                                          error_location  linea_num                                                error_message error_code                     timestamp\n0  fe1d71c8-8485-4a9d-b9ee-051bfc6c4f86  new_job  print_valor  File \"C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py\", line 106, in print_valor\\n    print(f\"Valor: {var}\")\\n                    ^^^        106  NameError: name 'var' is not defined. Did you mean: 'vars'?    'vars'? 2025-03-27 18:30:09.391006470", "name": "dagster", "pathname": "C:\\Users\\AxelRam\u00edrez\\Documents\\GitHub\\dagsters_tutorial\\getting_started_etl_tutorial\\etl_tutorial\\definitions.py", "process": 36232, "processName": "MainProcess", "relativeCreated": 44112.59436607361, "stack_info": null, "taskName": null, "thread": 11192, "threadName": "ThreadPoolExecutor-0_0"}
